config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  get 'login/index'
  resources :registers
  resources :reports
  resources :events do
    member do
      post "vote"#, to: "events#upvote"
      post "downvote"#, to: "events#downvote"
    end
    resources :comments
  end
  resources :users
  resources :home
  
  #root 'users#index'
  #root 'events#index'
  #root 'reports#index'
  root 'static_pages#homepage'
  #root 'registers#index'
  get 'static' => 'static_pages#static'
  get 'howto' => 'static_pages#howto'
  get  'about' => 'static_pages#about'
  get  'contact'  => 'static_pages#contact'
  get  'homepage'  => 'static_pages#homepage'
  #get 'users/index'
  get 'events/index'
  #get 'reports/index'
  #get 'login/index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'registers#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'homeevent', to: 'static_pages#homepage', as: 'homeevent'
  get 'back', to: 'static_pages#static', as: 'back'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>I'm in Status..</h1>
<p id="notice"><%= notice %></p>
<% if current_register %>
  Your welcome ! <br>
  Logged in as <%= current_register.username %>.<br>
  Your infomation<br>
  <%= image_tag current_register.image_url.to_s,style:"height: 100px; width: 100px;" %><br>
  Username : <%= current_register.username %><br>
  Email    : <%= current_register.email %><br>
  Phone    : <%= current_register.phone %><br>
  <%= link_to "Log Out", logout_path %>
  <%= link_to "Destroy",current_register, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to "Edit", edit_register_path(current_register) %>
  <%= link_to "Back", homeevent_path %>
<% else %>
  <%= link_to "Sign Up", signup_path  %> or
  <%= link_to "Log In", login_path %>
<% end %>