config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  get 'login/index'
  resources :registers
  resources :reports
  resources :events do
    member do
      post "vote"#, to: "events#upvote"
      post "downvote"#, to: "events#downvote"
    end
    resources :comments
  end
  resources :users
  resources :home
  
  #root 'users#index'
  #root 'events#index'
  #root 'reports#index'
  root 'static_pages#homepage'
  #root 'registers#index'
  get 'static' => 'static_pages#static'
  get 'howto' => 'static_pages#howto'
  get  'about' => 'static_pages#about'
  get  'contact'  => 'static_pages#contact'
  get  'homepage'  => 'static_pages#homepage'
  #get 'users/index'
  get 'events/index'
  #get 'reports/index'
  #get 'login/index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'registers#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'homeevent', to: 'static_pages#homepage', as: 'homeevent'
  get 'back', to: 'static_pages#static', as: 'back'
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true
    validates :category, presence: true
    validates :description, presence: true
    validates :phone, presence: true 
    belongs_to :register
    acts_as_votable
    has_many :comments
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    #@events = Event.all
  end

  # GET /events/new
  def new
    @event = current_register.events.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_register.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def vote
    @event = Event.find(params[:id])
    @event.upvote_by current_register
    redirect_back fallback_location: root_path
  end
    
  def downvote
    @event = Event.find(params[:id])
    @event.downvote_by current_register
    redirect_back fallback_location: root_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :category, :description, :by ,:start, :end, :phone)
    end
    

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :category
    = f.select :category,['food','concert','movie','sport','travel','game','university','ete']
  .field
    = f.label :description
    = f.text_area :description ,:cols => 70, :rows => 20
  .field
    = f.label :by
    = f.text_field :by
  .field
    = f.label :start
    = f.date_select :start
  .field
    = f.label :end
    = f.date_select  :end
  .field
    = f.label :phone
    = f.text_field :phone
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
= link_to 'Back', events_path
/*= link_to 'Back',homeevent_path

app/views/events/index.html.haml
%p#notice= notice

%h1 Events

%table
  %thead
    %tr
      %th Title
      %th Category
      %th Description
      %th By
      %th Start
      %th End
      %th Phone
      %th 
      %th 
      %th 

  %tbody
    - @events.each do |event|
      %tr
        %td= event.title
        %td= event.category
        %td= event.description
        %td= event.by
        %td= event.start
        %td= event.end
        %td= event.phone
        %td= link_to 'Show', event
        
        %td= link_to 'Edit', edit_event_path(event)
        %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }
        

= link_to 'New Event', new_event_path
= link_to 'Back',root_url

app/views/events/new.html.haml
%h1 New event

= render 'form'

/*= link_to 'Back', events_path

= link_to 'Back',homeevent_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @event.title
%p
  %b Category:
  = @event.category
%p
  %b Description:
  = @event.description
%p
  %b By:
  = @event.by
%p
  %b Username:
  = @event.register.username  
%p
  %b Start:
  = @event.start
%p
  %b End:
  = @event.end
%p
  %b Phone:
  = @event.phone

%tr
  = link_to vote_event_path(@event), method: :post do
    %button Upvote
    = @event.get_upvotes.size
  = link_to downvote_event_path(@event), method: :post do
    %button Downvote
    = @event.get_downvotes.size  
%br
%h2
  = @event.comments.count
  comments
= render :partial => @event.comments
= simple_form_for [@event, Comment.new] do |f|
  = f.text_area :body
  = f.submit "Add comment"

%br
- if @event.register_id = current_register
  = link_to 'Edit', edit_event_path(@event)
  = link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }
/*= link_to 'Back', events_path
= link_to 'Back',homeevent_path